apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vpa-prometheus-exporter.fullname" . }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - autoscaling.k8s.io
    resources:
      - verticalpodautoscalers
